### ISSUE TITLE
Failure in Tests

### ISSUE THREAD

**Issue by A91y** [FOSS-Community/paste.py#26]
While running tests once, `test_delete_paste_route()` runs, which deletes the `test` paste and if the tests are run again, then the cases `test_get_paste_route()` and `test_delete_paste_route()` fails.

**Comment by Mr-Sunglasses** [comment]
@A91y yeah I know this we can do two things

1 - Use mock tests
2 - create a sample file and then delete that file.

**Comment by A91y** [comment]
Got it! So, can we go with the second option of creating a sample file and then deleting it? or create the `test` file again after deleting in the test case?
