### ISSUE TITLE
[Bug] `/docs` and `/redocs` are accessible in production 

### ISSUE THREAD

**Issue by SAMAD101** [FOSS-Community/paste.py#42]
## Reproduction
go to [/docs](https://paste.fosscu.org/docs) and [/redoc](https://paste.fosscu.org/redoc)

## Expectation
Should not accessible in production.

## Screenshots
![image](https://github.com/FOSS-Community/paste.py/assets/71956678/d9a2fa85-214a-4e2d-b2f8-7db9cc72753e)
![image](https://github.com/FOSS-Community/paste.py/assets/71956678/25c86217-f58e-4f46-a569-c6949e29a72c)

## Environment
Production

**Comment by Mr-Sunglasses** [comment]
@SAMAD101 we can use redocs in prod, and can remove openapi docs.
