### ISSUE TITLE
[Feature] : Create a SDK

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/paste.py#61]
Create a Python SDK that can help people to efficiently use the paste.py in there project.

**Comment by Utkarsh4517** [comment]
Up for work, can you assign it to me @Mr-Sunglasses

**Comment by Utkarsh4517** [comment]
@Mr-Sunglasses Are you going to create a new repo for this, or in the same dir?

**Comment by Mr-Sunglasses** [comment]
> @Mr-Sunglasses Are you going to create a new repo for this, or in the same dir?

Same repo, just made a `directory` name sdk.
